#CI项目
name: QCA-ALL

#CI计划
on:
  #自动编译：当Auto-Clean运行完成后
  # workflow_run:
  #   workflows: ["Auto-Clean"]
  #   types:
  #     - completed
  # #自动清理：每天早上2点
  schedule:
    - cron: 0 18 * * *

#CI权限
permissions: write-all

#CI任务
jobs:
  config:
    name: ${{matrix.TARGET}}
    strategy:
      fail-fast: false
      #max-parallel: 3
      matrix:
        TARGET: [IPQ60XX-WIFI-YES]
        SOURCE: [VIKINGYFY/immortalwrt]

    #调用公用编译核心WRT-CORE.yml
    uses: ./.github/workflows/WRT-CORE.yml
    with:
      #编译平台
      WRT_TARGET: ${{matrix.TARGET}}
      #默认主题
      WRT_THEME: argon
      #默认主机名
      WRT_NAME: IPQ6000
      #默认WIFI名
      WRT_WIFI: IPQ6000
      #默认地址
      WRT_IP: 192.168.8.1
      #默认密码，仅作提示，修改无用
      WRT_PW: 无
      #源码链接
      WRT_REPO: https://github.com/${{matrix.SOURCE}}.git
      #源码分支
      WRT_BRANCH: ${{matrix.BRANCH || 'main'}}
      #源码名称
      WRT_SOURCE: ${{matrix.SOURCE}}
