#CI项目
name: QCA-ALL

#CI计划
on:
  #自动编译：当Auto-Clean运行完成后
  # workflow_run:
  #   workflows: ["Auto-Clean"]
  #   types:
  #     - completed
  # #自动清理：每周五下午2点
  schedule:
    - cron: 0 14 * * 5
  
  workflow_dispatch:

#CI权限
permissions: write-all

#CI任务
jobs:
  config:
    name: ${{matrix.TARGET}}
    strategy:
      fail-fast: false
      #max-parallel: 3
      matrix:
        TARGET: [R2S]
        SOURCE: [immortalwrt/immortalwrt]

    #调用公用编译核心WRT-CORE.yml
    uses: ./.github/workflows/immortalwrt.yml
    with:
      #编译平台
      wrt_target: ${{matrix.TARGET}}
      #默认主机名
      wrt_name: RK3328
      #默认地址
      wrt_ip: 192.168.8.1
      #源码链接
      wrt_repo: https://github.com/${{matrix.SOURCE}}.git
      #源码分支
      wrt_branch: ${{matrix.BRANCH || 'main'}}
      #源码名称
      wrt_source: ${{matrix.SOURCE}}